export const browserCoreExamples = [
  "culturabuilder browser status",
  "culturabuilder browser start",
  "culturabuilder browser stop",
  "culturabuilder browser tabs",
  "culturabuilder browser open https://example.com",
  "culturabuilder browser focus abcd1234",
  "culturabuilder browser close abcd1234",
  "culturabuilder browser screenshot",
  "culturabuilder browser screenshot --full-page",
  "culturabuilder browser screenshot --ref 12",
  "culturabuilder browser snapshot",
  "culturabuilder browser snapshot --format aria --limit 200",
  "culturabuilder browser snapshot --efficient",
  "culturabuilder browser snapshot --labels",
];

export const browserActionExamples = [
  "culturabuilder browser navigate https://example.com",
  "culturabuilder browser resize 1280 720",
  "culturabuilder browser click 12 --double",
  'culturabuilder browser type 23 "hello" --submit',
  "culturabuilder browser press Enter",
  "culturabuilder browser hover 44",
  "culturabuilder browser drag 10 11",
  "culturabuilder browser select 9 OptionA OptionB",
  "culturabuilder browser upload /tmp/file.pdf",
  'culturabuilder browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "culturabuilder browser dialog --accept",
  'culturabuilder browser wait --text "Done"',
  "culturabuilder browser evaluate --fn '(el) => el.textContent' --ref 7",
  "culturabuilder browser console --level error",
  "culturabuilder browser pdf",
];
